import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import { getServerSession } from "next-auth";
import { options } from "@/lib/authOptions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vanista - Online E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  authModal,
}: {
  children: React.ReactNode;
  authModal: React.ReactNode;
}) {
  const session = getServerSession(options);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={session}>
          {children}
          {authModal}
        </Providers>
      </body>
    </html>
  );
}
